name: respiritdeviceapp
description: Respirit Device App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.31.15
  serial_port_win32: ^2.1.12
  flutter_libserialport: ^0.5.0
  serial: ^0.0.7+1
  libserialport: ^0.4.0
  embedded_serialport: ^1.5.5
  dart_serial: ^0.1.0-alpha.2
  serialport_plus: ^0.1.0
  usb_serial: ^0.5.2
  flutter_bluetooth_serial: ^0.4.0
  web_socket_channel: ^3.0.3
  network_info_plus: ^4.1.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  pdf: ^3.8.4
  printing: ^5.10.0
  cross_file: ^0.3.3
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^29.2.4
  convert: ^3.1.2
  widgets_to_image: ^1.0.0
  widget_to_marker: ^1.0.6
  provider: ^6.1.1
  http: ^1.2.0
  multicast_dns: ^0.3.3
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  flutter_reactive_ble: ^5.3.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/respirit.png
    - assets/respirit.png
    - assets/icons/app_icon.png
    - assets/icons/app_icon_foreground.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

dependency_overrides:
  libserialport: ^0.3.0
  flutter_libserialport: ^0.5.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/respirit.png
  android_12:
    image: assets/images/respirit.png
    icon_background_color: "#FFFFFF"
  web: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
